// Code generated by go-enum DO NOT EDIT.
// Version: 0.6.0
// Revision: 919e61c0174b91303753ee3898569a01abb32c97
// Build Date: 2023-12-18T15:54:43Z
// Built By: goreleaser

package enums

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strconv"
)

const (
	// DeviceStateTypeAvailable is a DeviceStateType of type available.
	DeviceStateTypeAvailable DeviceStateType = "available"
	// DeviceStateTypeUsing is a DeviceStateType of type using.
	DeviceStateTypeUsing DeviceStateType = "using"
	// DeviceStateTypeDischarged is a DeviceStateType of type discharged.
	DeviceStateTypeDischarged DeviceStateType = "discharged"
	// DeviceStateTypeFixing is a DeviceStateType of type fixing.
	DeviceStateTypeFixing DeviceStateType = "fixing"
)

var ErrInvalidDeviceStateType = errors.New("not a valid DeviceStateType")

// String implements the Stringer interface.
func (x DeviceStateType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DeviceStateType) IsValid() bool {
	_, err := ParseDeviceStateType(string(x))
	return err == nil
}

var _DeviceStateTypeValue = map[string]DeviceStateType{
	"available":  DeviceStateTypeAvailable,
	"using":      DeviceStateTypeUsing,
	"discharged": DeviceStateTypeDischarged,
	"fixing":     DeviceStateTypeFixing,
}

// ParseDeviceStateType attempts to convert a string to a DeviceStateType.
func ParseDeviceStateType(name string) (DeviceStateType, error) {
	if x, ok := _DeviceStateTypeValue[name]; ok {
		return x, nil
	}
	return DeviceStateType(""), fmt.Errorf("%s is %w", name, ErrInvalidDeviceStateType)
}

// MarshalText implements the text marshaller method.
func (x DeviceStateType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *DeviceStateType) UnmarshalText(text []byte) error {
	tmp, err := ParseDeviceStateType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errDeviceStateTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

var sqlIntDeviceStateTypeMap = map[int64]DeviceStateType{
	1: DeviceStateTypeAvailable,
	2: DeviceStateTypeUsing,
	3: DeviceStateTypeDischarged,
	4: DeviceStateTypeFixing,
}

var sqlIntDeviceStateTypeValue = map[DeviceStateType]int64{
	DeviceStateTypeAvailable:  1,
	DeviceStateTypeUsing:      2,
	DeviceStateTypeDischarged: 3,
	DeviceStateTypeFixing:     4,
}

func lookupSqlIntDeviceStateType(val int64) (DeviceStateType, error) {
	x, ok := sqlIntDeviceStateTypeMap[val]
	if !ok {
		return x, fmt.Errorf("%v is not %w", val, ErrInvalidDeviceStateType)
	}
	return x, nil
}

// Scan implements the Scanner interface.
func (x *DeviceStateType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = DeviceStateType("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x, err = lookupSqlIntDeviceStateType(v)
	case string:
		*x, err = ParseDeviceStateType(v)
	case []byte:
		if val, verr := strconv.ParseInt(string(v), 10, 64); verr == nil {
			*x, err = lookupSqlIntDeviceStateType(val)
		} else {
			// try parsing the value as a string
			*x, err = ParseDeviceStateType(string(v))
		}
	case DeviceStateType:
		*x = v
	case int:
		*x, err = lookupSqlIntDeviceStateType(int64(v))
	case *DeviceStateType:
		if v == nil {
			return errDeviceStateTypeNilPtr
		}
		*x = *v
	case uint:
		*x, err = lookupSqlIntDeviceStateType(int64(v))
	case uint64:
		*x, err = lookupSqlIntDeviceStateType(int64(v))
	case *int:
		if v == nil {
			return errDeviceStateTypeNilPtr
		}
		*x, err = lookupSqlIntDeviceStateType(int64(*v))
	case *int64:
		if v == nil {
			return errDeviceStateTypeNilPtr
		}
		*x, err = lookupSqlIntDeviceStateType(int64(*v))
	case float64: // json marshals everything as a float64 if it's a number
		*x, err = lookupSqlIntDeviceStateType(int64(v))
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errDeviceStateTypeNilPtr
		}
		*x, err = lookupSqlIntDeviceStateType(int64(*v))
	case *uint:
		if v == nil {
			return errDeviceStateTypeNilPtr
		}
		*x, err = lookupSqlIntDeviceStateType(int64(*v))
	case *uint64:
		if v == nil {
			return errDeviceStateTypeNilPtr
		}
		*x, err = lookupSqlIntDeviceStateType(int64(*v))
	case *string:
		if v == nil {
			return errDeviceStateTypeNilPtr
		}
		*x, err = ParseDeviceStateType(*v)
	default:
		return errors.New("invalid type for DeviceStateType")
	}

	return
}

// Value implements the driver Valuer interface.
func (x DeviceStateType) Value() (driver.Value, error) {
	val, ok := sqlIntDeviceStateTypeValue[x]
	if !ok {
		return nil, ErrInvalidDeviceStateType
	}
	return int64(val), nil
}
