// Code generated by go-enum DO NOT EDIT.
// Version: 0.6.0
// Revision: 919e61c0174b91303753ee3898569a01abb32c97
// Build Date: 2023-12-18T15:54:43Z
// Built By: goreleaser

package enums

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strconv"
)

const (
	// IssueStatusStatusTypeNormal is a IssueStatusStatusType of type normal.
	IssueStatusStatusTypeNormal IssueStatusStatusType = "normal"
	// IssueStatusStatusTypeSystem is a IssueStatusStatusType of type system.
	IssueStatusStatusTypeSystem IssueStatusStatusType = "system"
)

var ErrInvalidIssueStatusStatusType = errors.New("not a valid IssueStatusStatusType")

// String implements the Stringer interface.
func (x IssueStatusStatusType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x IssueStatusStatusType) IsValid() bool {
	_, err := ParseIssueStatusStatusType(string(x))
	return err == nil
}

var _IssueStatusStatusTypeValue = map[string]IssueStatusStatusType{
	"normal": IssueStatusStatusTypeNormal,
	"system": IssueStatusStatusTypeSystem,
}

// ParseIssueStatusStatusType attempts to convert a string to a IssueStatusStatusType.
func ParseIssueStatusStatusType(name string) (IssueStatusStatusType, error) {
	if x, ok := _IssueStatusStatusTypeValue[name]; ok {
		return x, nil
	}
	return IssueStatusStatusType(""), fmt.Errorf("%s is %w", name, ErrInvalidIssueStatusStatusType)
}

// MarshalText implements the text marshaller method.
func (x IssueStatusStatusType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *IssueStatusStatusType) UnmarshalText(text []byte) error {
	tmp, err := ParseIssueStatusStatusType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errIssueStatusStatusTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

var sqlIntIssueStatusStatusTypeMap = map[int64]IssueStatusStatusType{
	1: IssueStatusStatusTypeNormal,
	2: IssueStatusStatusTypeSystem,
}

var sqlIntIssueStatusStatusTypeValue = map[IssueStatusStatusType]int64{
	IssueStatusStatusTypeNormal: 1,
	IssueStatusStatusTypeSystem: 2,
}

func lookupSqlIntIssueStatusStatusType(val int64) (IssueStatusStatusType, error) {
	x, ok := sqlIntIssueStatusStatusTypeMap[val]
	if !ok {
		return x, fmt.Errorf("%v is not %w", val, ErrInvalidIssueStatusStatusType)
	}
	return x, nil
}

// Scan implements the Scanner interface.
func (x *IssueStatusStatusType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = IssueStatusStatusType("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x, err = lookupSqlIntIssueStatusStatusType(v)
	case string:
		*x, err = ParseIssueStatusStatusType(v)
	case []byte:
		if val, verr := strconv.ParseInt(string(v), 10, 64); verr == nil {
			*x, err = lookupSqlIntIssueStatusStatusType(val)
		} else {
			// try parsing the value as a string
			*x, err = ParseIssueStatusStatusType(string(v))
		}
	case IssueStatusStatusType:
		*x = v
	case int:
		*x, err = lookupSqlIntIssueStatusStatusType(int64(v))
	case *IssueStatusStatusType:
		if v == nil {
			return errIssueStatusStatusTypeNilPtr
		}
		*x = *v
	case uint:
		*x, err = lookupSqlIntIssueStatusStatusType(int64(v))
	case uint64:
		*x, err = lookupSqlIntIssueStatusStatusType(int64(v))
	case *int:
		if v == nil {
			return errIssueStatusStatusTypeNilPtr
		}
		*x, err = lookupSqlIntIssueStatusStatusType(int64(*v))
	case *int64:
		if v == nil {
			return errIssueStatusStatusTypeNilPtr
		}
		*x, err = lookupSqlIntIssueStatusStatusType(int64(*v))
	case float64: // json marshals everything as a float64 if it's a number
		*x, err = lookupSqlIntIssueStatusStatusType(int64(v))
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errIssueStatusStatusTypeNilPtr
		}
		*x, err = lookupSqlIntIssueStatusStatusType(int64(*v))
	case *uint:
		if v == nil {
			return errIssueStatusStatusTypeNilPtr
		}
		*x, err = lookupSqlIntIssueStatusStatusType(int64(*v))
	case *uint64:
		if v == nil {
			return errIssueStatusStatusTypeNilPtr
		}
		*x, err = lookupSqlIntIssueStatusStatusType(int64(*v))
	case *string:
		if v == nil {
			return errIssueStatusStatusTypeNilPtr
		}
		*x, err = ParseIssueStatusStatusType(*v)
	default:
		return errors.New("invalid type for IssueStatusStatusType")
	}

	return
}

// Value implements the driver Valuer interface.
func (x IssueStatusStatusType) Value() (driver.Value, error) {
	val, ok := sqlIntIssueStatusStatusTypeValue[x]
	if !ok {
		return nil, ErrInvalidIssueStatusStatusType
	}
	return int64(val), nil
}
