// Code generated by go-enum DO NOT EDIT.
// Version: 0.6.0
// Revision: 919e61c0174b91303753ee3898569a01abb32c97
// Build Date: 2023-12-18T15:54:43Z
// Built By: goreleaser

package enums

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strconv"
)

const (
	// ProjectStateKanban is a ProjectState of type active.
	ProjectStateActive ProjectState = "active"
	// ProjectStateScrum is a ProjectState of type inactive.
	ProjectStateInactive ProjectState = "inactive"
)

var ErrInvalidProjectState = errors.New("not a valid ProjectState")

// String implements the Stringer interface.
func (x ProjectState) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ProjectState) IsValid() bool {
	_, err := ParseProjectState(string(x))
	return err == nil
}

var _ProjectStateValue = map[string]ProjectState{
	"active":  ProjectStateActive,
	"inactive": ProjectStateInactive,
}

// ParseProjectState attempts to convert a string to a ProjectState.
func ParseProjectState(name string) (ProjectState, error) {
	if x, ok := _ProjectStateValue[name]; ok {
		return x, nil
	}
	return ProjectState(""), fmt.Errorf("%s is %w", name, ErrInvalidProjectState)
}

// MarshalText implements the text marshaller method.
func (x ProjectState) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ProjectState) UnmarshalText(text []byte) error {
	tmp, err := ParseProjectState(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errProjectStateNilPtr = errors.New("value pointer is nil") // one per type for package clashes

var sqlIntProjectStateMap = map[int64]ProjectState{
	1: ProjectStateActive,
	2: ProjectStateInactive,
}

var sqlIntProjectStateValue = map[ProjectState]int64{
	ProjectStateActive:  1,
	ProjectStateInactive: 2,
}

func lookupSqlIntProjectState(val int64) (ProjectState, error) {
	x, ok := sqlIntProjectStateMap[val]
	if !ok {
		return x, fmt.Errorf("%v is not %w", val, ErrInvalidProjectState)
	}
	return x, nil
}

// Scan implements the Scanner interface.
func (x *ProjectState) Scan(value interface{}) (err error) {
	if value == nil {
		*x = ProjectState("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x, err = lookupSqlIntProjectState(v)
	case string:
		*x, err = ParseProjectState(v)
	case []byte:
		if val, verr := strconv.ParseInt(string(v), 10, 64); verr == nil {
			*x, err = lookupSqlIntProjectState(val)
		} else {
			// try parsing the value as a string
			*x, err = ParseProjectState(string(v))
		}
	case ProjectState:
		*x = v
	case int:
		*x, err = lookupSqlIntProjectState(int64(v))
	case *ProjectState:
		if v == nil {
			return errProjectStateNilPtr
		}
		*x = *v
	case uint:
		*x, err = lookupSqlIntProjectState(int64(v))
	case uint64:
		*x, err = lookupSqlIntProjectState(int64(v))
	case *int:
		if v == nil {
			return errProjectStateNilPtr
		}
		*x, err = lookupSqlIntProjectState(int64(*v))
	case *int64:
		if v == nil {
			return errProjectStateNilPtr
		}
		*x, err = lookupSqlIntProjectState(int64(*v))
	case float64: // json marshals everything as a float64 if it's a number
		*x, err = lookupSqlIntProjectState(int64(v))
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errProjectStateNilPtr
		}
		*x, err = lookupSqlIntProjectState(int64(*v))
	case *uint:
		if v == nil {
			return errProjectStateNilPtr
		}
		*x, err = lookupSqlIntProjectState(int64(*v))
	case *uint64:
		if v == nil {
			return errProjectStateNilPtr
		}
		*x, err = lookupSqlIntProjectState(int64(*v))
	case *string:
		if v == nil {
			return errProjectStateNilPtr
		}
		*x, err = ParseProjectState(*v)
	default:
		return errors.New("invalid type for ProjectState")
	}

	return
}

// Value implements the driver Valuer interface.
func (x ProjectState) Value() (driver.Value, error) {
	val, ok := sqlIntProjectStateValue[x]
	if !ok {
		return nil, ErrInvalidProjectState
	}
	return int64(val), nil
}
