// Code generated by go-enum DO NOT EDIT.
// Version: 0.6.0
// Revision: 919e61c0174b91303753ee3898569a01abb32c97
// Build Date: 2023-12-18T15:54:43Z
// Built By: goreleaser

package enums

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strconv"
)

const (
	// ProjectTypeKanban is a ProjectType of type kanban.
	ProjectTypeKanban ProjectType = "kanban"
	// ProjectTypeScrum is a ProjectType of type scrum.
	ProjectTypeScrum ProjectType = "scrum"
)

var ErrInvalidProjectType = errors.New("not a valid ProjectType")

// String implements the Stringer interface.
func (x ProjectType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ProjectType) IsValid() bool {
	_, err := ParseProjectType(string(x))
	return err == nil
}

var _ProjectTypeValue = map[string]ProjectType{
	"kanban": ProjectTypeKanban,
	"scrum":  ProjectTypeScrum,
}

// ParseProjectType attempts to convert a string to a ProjectType.
func ParseProjectType(name string) (ProjectType, error) {
	if x, ok := _ProjectTypeValue[name]; ok {
		return x, nil
	}
	return ProjectType(""), fmt.Errorf("%s is %w", name, ErrInvalidProjectType)
}

// MarshalText implements the text marshaller method.
func (x ProjectType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ProjectType) UnmarshalText(text []byte) error {
	tmp, err := ParseProjectType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errProjectTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

var sqlIntProjectTypeMap = map[int64]ProjectType{
	1: ProjectTypeKanban,
	2: ProjectTypeScrum,
}

var sqlIntProjectTypeValue = map[ProjectType]int64{
	ProjectTypeKanban: 1,
	ProjectTypeScrum:  2,
}

func lookupSqlIntProjectType(val int64) (ProjectType, error) {
	x, ok := sqlIntProjectTypeMap[val]
	if !ok {
		return x, fmt.Errorf("%v is not %w", val, ErrInvalidProjectType)
	}
	return x, nil
}

// Scan implements the Scanner interface.
func (x *ProjectType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = ProjectType("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x, err = lookupSqlIntProjectType(v)
	case string:
		*x, err = ParseProjectType(v)
	case []byte:
		if val, verr := strconv.ParseInt(string(v), 10, 64); verr == nil {
			*x, err = lookupSqlIntProjectType(val)
		} else {
			// try parsing the value as a string
			*x, err = ParseProjectType(string(v))
		}
	case ProjectType:
		*x = v
	case int:
		*x, err = lookupSqlIntProjectType(int64(v))
	case *ProjectType:
		if v == nil {
			return errProjectTypeNilPtr
		}
		*x = *v
	case uint:
		*x, err = lookupSqlIntProjectType(int64(v))
	case uint64:
		*x, err = lookupSqlIntProjectType(int64(v))
	case *int:
		if v == nil {
			return errProjectTypeNilPtr
		}
		*x, err = lookupSqlIntProjectType(int64(*v))
	case *int64:
		if v == nil {
			return errProjectTypeNilPtr
		}
		*x, err = lookupSqlIntProjectType(int64(*v))
	case float64: // json marshals everything as a float64 if it's a number
		*x, err = lookupSqlIntProjectType(int64(v))
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errProjectTypeNilPtr
		}
		*x, err = lookupSqlIntProjectType(int64(*v))
	case *uint:
		if v == nil {
			return errProjectTypeNilPtr
		}
		*x, err = lookupSqlIntProjectType(int64(*v))
	case *uint64:
		if v == nil {
			return errProjectTypeNilPtr
		}
		*x, err = lookupSqlIntProjectType(int64(*v))
	case *string:
		if v == nil {
			return errProjectTypeNilPtr
		}
		*x, err = ParseProjectType(*v)
	default:
		return errors.New("invalid type for ProjectType")
	}

	return
}

// Value implements the driver Valuer interface.
func (x ProjectType) Value() (driver.Value, error) {
	val, ok := sqlIntProjectTypeValue[x]
	if !ok {
		return nil, ErrInvalidProjectType
	}
	return int64(val), nil
}
